### ISSUE TITLE
How about not bundling the schemas, instead fetching and store them at runtime?

### ISSUE THREAD

**Issue by JounQin** [ota-meshi/eslint-plugin-json-schema-validator#152]
IMO the schmas should not be bundled into package, most ot the files are useless for most users, they should be downloaded and cached lazily.

**Comment by ota-meshi** [comment]
I agree that bundling all schemas is useless for most users.
However, I think it's better to bundle some commonly used schemas for better rule performance.
It may make sense to change it to bundle only the schemas that are commonly used in front-end development. What do you think?

**Comment by JounQin** [comment]
> However, I think it's better to bundle some commonly used schemas for better rule performance.

With global `cache` support, it should not be a problem?

**Comment by JounQin** [comment]
There is a build error displaying package size on [bundlephobia](https://bundlephobia.com/package/eslint-plugin-json-schema-validator). 😅

**Comment by ota-meshi** [comment]
This plugin already has a cache mechanism.
The schema that this plugin does not bundle is cached as a file in the directory of `eslint-plugin-json-schema-validator/.cached_schemastore` for 1 day after getting it by HTTP.
However, this is not intended to improve the user experience, but because we do not want to make many requests to the server where the schema is stored. Also, the cache may not be available on CI.
Perhaps most of the schema is stored in `json.schemastore.org`, so not bundling `json.schemastore.org` can put a lot of load on `json.schemastore.org`.

**Comment by ota-meshi** [comment]
> There is a build error displaying package size on bundlephobia. 😅

This plugin is not intended to be bundled and used, so I think it's okay. is not it? 🤔

**Comment by JounQin** [comment]
> > There is a build error displaying package size on bundlephobia. 😅
> 
> This plugin is not intended to be bundled and used, so I think it's okay. is not it? 🤔

I'm just trying to explore how much the npm package costs.

**Comment by ota-meshi** [comment]
> I'm just trying to explore how much the npm package costs.

Can't you use what is displayed on npm?

https://www.npmjs.com/package/eslint-plugin-json-schema-validator

<img width="374" alt="image" src="https://user-images.githubusercontent.com/16508807/177084155-48bf8c45-104f-4a78-9bd7-806158dd01e9.png">

**Comment by JounQin** [comment]
> Perhaps most of the schema is stored in json.schemastore.org, so not bundling json.schemastore.org can put a lot of load on json.schemastore.org.

Should this be considered too much? When the user open files in Editor, a lot of editors like VSCode will try to fetch the schema automatically already. And if you only process the schemas the user are going to use, that should be OK IMO.

> Can't you use what is displayed on npm?

Thanks for pointing this to me, I didn't notice it before. 😂

4.7 MB for a `eslint-plugin` without any dependencies cost is a bit too large to me.

**Comment by ota-meshi** [comment]
> Should this be considered too much? 

If not considered at all, it may be considered a DoS attack. So I think it should at least be considered.
When running in CI, it is possible to make consecutive HTTP requests without intervals to validate multiple files.

**Comment by JounQin** [comment]
For CI purpose, it can be added into CI cache, we can bundle them only for CI, and exclude them from `npm` package?

**Comment by ota-meshi** [comment]
I didn't know the details of your idea. Could you explain the details?

**Comment by JounQin** [comment]
I mean we can still bundle them, but only for CI, and add them to CI cache, there should be no DoS attack due to cache.

For `npm`, we remove `schemastore` in `files`, and get schema on runtime and machine global cache:

```diff
   "files": [
     "lib",
-    "schemastore"
   ]
```

**Comment by ota-meshi** [comment]
Hmm. I don't understand yet.
How do users use excluded store data?

**Comment by JounQin** [comment]
> Hmm. I don't understand yet. How do users use excluded store data?

`fetch` the schema they need on runtime and store into cache for reusing.

**Comment by ota-meshi** [comment]
(I may have misunderstood you.)
I don't think it resolves the possibility that users may be considered to be doing DoS attacks using CI.
I'm not worried about our CI.

**Comment by JounQin** [comment]
Oh, thanks for explanation.

For common users, they should have only a few schemas to fetch at runtime?

For bad guys, they can do DoS attacks without this plugin at all.

I still think you don't need to consider such cases.

And also, the changes are very small, just remove `schemastore` from `files` field, if any bad things happen (I suppose never), we can just add it back easily.

**Comment by ota-meshi** [comment]
> just remove schemastore from files field

Probably not the just one. Currently catalog data is not reacquired via HTTP.
