### ISSUE TITLE
Relative $schema URIs should be resolved against the file's path, not the cwd

### ISSUE THREAD

**Issue by nspire909** [ota-meshi/eslint-plugin-json-schema-validator#154]
First of all thank you for adding $schema support, I can now remove the corresponding redundant eslint config. However, relative schema URIs are being resolved against the cwd (line 47 in schema.ts). This makes sense for schemas defined in .eslintrc, but relative URIs in a json file need to be resolved relative to the file.

**Comment by JounQin** [comment]
https://github.com/ota-meshi/eslint-plugin-json-schema-validator/blob/25e1df1581f17fb1aa259e8ef53080442d1ac165/src/utils/schema.ts#L47

Would you like to raise a PR to contribute?

**Comment by nspire909** [comment]
Yes. I will submit a PR tomorrow.

**Comment by JounQin** [comment]
> Yes. I will submit a PR tomorrow.

A tiny notice, we are targeting `eslint >= 6.0.0`, so `context. getPhysicalFilename` could be unavailable, if so a fallback function should be used like:

https://github.com/mdx-js/eslint-mdx/blob/b97db2e912a416d5d40ddb78ab6c9fa1ab150c17/packages/eslint-mdx/src/helpers.ts#L28-L50
