### ISSUE TITLE
`$schema` with url is not supported

### ISSUE THREAD

**Issue by JounQin** [ota-meshi/eslint-plugin-json-schema-validator#166]
```json
{
  "$schema": "https://raw.githubusercontent.com/Septh/tmlanguage/master/tmLanguage.schema.json"
}
```

https://github.com/mdx-js/vscode-mdx/blob/3af040bb5918dbcda868fed486574b8a3b0fb1b1/syntaxes/mdx.tmLanguage.json#L2

**Comment by ota-meshi** [comment]
I tried with your file and I think it's working. Do you have more detailed information to reproduce?

<img width="895" alt="image" src="https://user-images.githubusercontent.com/16508807/183099992-d0f30035-aa83-4e03-ba05-667e0fafb470.png">

**Comment by JounQin** [comment]
Interesting, I tried to run `yarn upgrade --latest` and the error like `the schema of path 'https://xxx' can not be resolved` is gone. Maybe I was on a old version. I'm closing this for now. 🤣
