### ISSUE TITLE
report incorrect trailing comma in JSON

### ISSUE THREAD

**Issue by bhsd-harry** [ota-meshi/eslint-plugin-json-schema-validator#204]
I often write invalid JSON files because the trailing commas are not deleted after some changes. Does this plugin help report this kind of errors? I am using the latest version of this plugin with `"extends": ["plugin:json-schema-validator/base"]`. I have also tried setting `"parserOptions": { "ecmaVersion": 3 }` or `"rules": { "comma-dangle": "error" }`, but none of them seems to work.

**Comment by ota-meshi** [comment]
I think you can use eslint-plugin-jsonc.
https://github.com/ota-meshi/eslint-plugin-jsonc

**Comment by bhsd-harry** [comment]
> I think you can use eslint-plugin-jsonc.

Thank you for your answer! My issue has been resolved.
