### ISSUE TITLE
Support extending $schema with plugin options

### ISSUE THREAD

**Issue by MarcRoemmelt** [ota-meshi/eslint-plugin-json-schema-validator#235]
## What do I want?
Instead of using only the schema referenced at the `$schemaPath`, I would like this plugin to validate the schema at `$schemaPath` together with all schemas defined in `option.schemas`.

## Why would this be useful?
I am working with a monorepo that uses a large number of generators to bootstrap new libraries. Many of these come with `.json` files with their dedicated JsonSchema referenced at `$schema`. If I want to add validations to the schema of certain files across the monorepo I currently have two options:
1. manually manage a large number of schema files and their imports
2. remove the $schema field and apply the original schemas and added validations in the configuration for this plugin
Both options are rather tedious and it would help a lot if there was an option to merge some additional validations into the existing `$schema`.

## What could this look like?
Based on the `boolean` configuration option `mergeSchema` we could add an additional `option.schemas` object for  the `$schemaPath`. E.g.

```typescript
// src/rules/no-invalid.ts:217
create(context, { filename }) {
  const $schemaPath = findSchemaPath(context.getSourceCode().ast);
  
  const mergeSchemas = context.options[0]?.mergeSchemas;

  let validator: Validator;
  if (!mergeSchemas && $schemaPath != null) { // Don't take this path if merging schemas
    const v = schemaPathToValidator($schemaPath, context);
    if (!v) {
      reportCannotResolvedPath($schemaPath, context);
      return {};
    }
    validator = v;
  } else {
    const cwd = getCwd(context);

    const option = context.options[0] || {};

    // Append the additional schema. If option.mergeSchemas is defined, option are not a string
    if (mergeSchemas && $schemaPath) {
        const $schemaValidator = { schema: $schemaPath, fileMatch: ['*'] };
        option.schemas = [$schemaSchema, ...(option.schemas || [])];
    }

    const v = parseOption(
      option,
      context,
      filename.startsWith(cwd) ? path.relative(cwd, filename) : filename,
    );
    if (!v) {
      return {};
    }
    validator = v;
  }
  // ...
```
I tested this already and it works smoothly. If this change is accepted, I would gladly take this up and create a PR! :)

**Comment by ota-meshi** [comment]
Thanks for the feature suggestions.
The new options look good, but I think we need to merge the schemas set in `$schema`, the `schemas` option of the rule, and the [catalog] schema.
If you only want to merge 2 of the 3 schemas, I think the new option should allow the user to choose their preference.

[catalog]: https://www.schemastore.org/api/json/catalog.json

**Comment by MarcRoemmelt** [comment]
That makes total sense!

The option could be `mergeSchemas`:
- `boolean` - merge all schema sources
- ['catalog', 'options', 'schemaPath'] - merge only those specified

What do you think?

**Comment by ota-meshi** [comment]
Sounds good to me 👍

**Comment by MarcRoemmelt** [comment]
> Sounds good to me 👍 

Awesome! Will open a PR when I find time for this (hopefully coming week).
