### ISSUE TITLE
Issue with schemastore website

### ISSUE THREAD

**Issue by zeroedin** [ota-meshi/eslint-plugin-json-schema-validator#253]
Cross linking in case others are running into similar issues: https://github.com/SchemaStore/schemastore/issues/3303

```bash
error  Specified schema could not be resolved. Path: "https://json.schemastore.org/package.json"  json-schema-validator/no-invalid
```

**Comment by hyperupcall** [comment]
The problem should now be fixed - the issue stemmed from the increase in requests hitting the ceiling of allocated memory/compute

**Comment by ota-meshi** [comment]
Thank you for posting the issue. I'll close this issue since it looks like it's already fixed.
