### ISSUE TITLE
List on json-schema.org

### ISSUE THREAD

**Issue by benjagm** [ota-meshi/eslint-plugin-json-schema-validator#281]
Hello! My name is Benjamin from the JSON Schema Community. I came across this cool JSON Schema implementation, and I wanted to congratulate for the great work! KUDOS!

I noticed that it's not listed on our [implementations page](https://json-schema.org/implementations.html), but we'd love it to be.
If you'd like to add this implementation to that page, please feel free to [create a pull request](https://github.com/json-schema-org/website/pulls)!

I'd like to use this opportunity to invite you to join the [JSON Schema Community in Slack](https://json-schema.org/slack), where we have some interesting channels like #implementers where you could connect with other relevant maintainers in the ecosystem.

Thanks for enhancing the JSON Schema ecosystem!

**Comment by ota-meshi** [comment]
Thank you for letting me know. I would like to submit a PR after https://github.com/json-schema-org/website/pull/247 is merged.

**Comment by benjagm** [comment]
> Thank you for letting me know. I would like to submit a PR after [json-schema-org/website#247](https://github.com/json-schema-org/website/pull/247) is merged.

Happy new year @ota-meshi ! We just wanted to let you know that PR has been merged and we'd love to add your plugin.
