### ISSUE TITLE
Timeout of 10000ms exceeded for get-modules/http.js

### ISSUE THREAD

**Issue by adamlui** [ota-meshi/eslint-plugin-json-schema-validator#323]
This used to happen once in a while, but now it is so frequent, I have to retry 3-4 times to make it go away

![image](https://github.com/ota-meshi/eslint-plugin-json-schema-validator/assets/10906554/2dd82953-5478-45ac-9896-9c6c56114e01)

from https://github.com/kudoai/bravegpt

**Comment by ota-meshi** [comment]
Pull requests are welcome, I think it should be made optional.

**Comment by ota-meshi** [comment]
I have changed the timeout to 60s. If you are still having problems, please open a new issue.

**Comment by adamlui** [comment]
I think that will just make it worse. Previously after 10s timeout, terminal just hangs around in limbo state, then sometimes ESLint finishes successfully, other times fails. Now, it will take a whole minute to timeout before proceeding to succeed/fail...

**Comment by adamlui** [comment]
You should just spy on how your biggest competitor bypasses having to rely on this unreliable module (i used them prior but switched since this also covered yaml, but if issue persists i'ma just switch back)

**Comment by ota-meshi** [comment]
I'm not sure what you want to change. Could you open a new issue and explain in more detail?

**Comment by adamlui** [comment]
But it's not a separate issue. get-modules/http.js makes your plugin unusable. I want to change using your plugin for your competitor's because no such issues exist in his working version

**Comment by adamlui** [comment]
I didn't change yet because I have like 30+ repos that use ESLint

**Comment by adamlui** [comment]
What I'm saying is your plugin does not work because of get-modules/http.js regardless of timeout duration, so you must replace this dependency or others will leave too

**Comment by adamlui** [comment]
This error occurs 100% of the time now

**Comment by ota-meshi** [comment]
> What I'm saying is your plugin does not work because of get-modules/http.js regardless of timeout duration, so you must replace this dependency or others will leave too

Still not sure? What is your suggestion?

**Comment by adamlui** [comment]
I said it 2 times don't use get-modules/http.js spy on the other json plugin see how they don't rely on it, just copy same thing

**Comment by adamlui** [comment]
Wait ignore me increased timeout worked

**Comment by ota-meshi** [comment]
How would we make this plugin work if we didn't use `get-modules/http.js`?

**Comment by adamlui** [comment]
However the other plugin makes it work without this sporadic issue

**Comment by adamlui** [comment]
If he's using same dependency then the implementation is just flawed

**Comment by ota-meshi** [comment]
> However the other plugin makes it work without this sporadic issue
I didn't know there was another ESLint plugin that has the same functionality as this one, and if it works well, it would make sense to use it. Could you please tell me which plugin it is, if possible?

**Comment by adamlui** [comment]
I'm busy but you can easily find it on search engine by typing something like ESLint JSON plugin

**Comment by ota-meshi** [comment]
Okay. I'll lock this thread then.
