### ISSUE TITLE
Disable HTTP Agent Timeout By Default

### ISSUE THREAD

**Issue by Kenneth-Sills** [ota-meshi/eslint-plugin-json-schema-validator#362]
Starting with Node 19, the [`globalAgent`](https://nodejs.org/api/http.html#httpglobalagent) used by default for `http(s).request` and `http(s).get` had the socket `timeout` set to a default 5 seconds ([described here](https://nodejs.org/api/http.html#class-httpagent)).

Without getting too into the weeds of how Node is implemented, with the way the [event loop](https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick) orders timer and I/O operations, combined with [ESLint's core being synchronous in design](https://github.com/eslint/eslint/issues/15394) (until the v10 rewrite), and the socket timeout timer starting *immediately* when the socket is made... ESLint on a large project or with many plugins enabled ends up consuming the entire CPU time and the socket never actually establishes a connection before timing out.

This is what led to #323 suddenly being an issue; it was less about how long our timeout is set for and more about the 5 second default timeout on the socket itself being triggered and causing our handler to trigger eroneously.

Luckily, you had great foresight with the `settings.http.requestOptions` setting! This can be worked around trivially by adding the following to your ESLint config:

```js
settings: {
    http: {
        requestOptions: {
            agent: false,
        },
    },
}
```

A proper fix would involve updating [`parseUrlAndOptions`](https://github.com/ota-meshi/eslint-plugin-json-schema-validator/blob/main/src/utils/http-client/get-modules/http.ts#L67) with that setting as the default.

**Comment by ota-meshi** [comment]
That sounds good to me! Pull requests are welcome.

**Comment by Kenneth-Sills** [comment]
@adamlui You may be interested in this.

**Comment by adamlui** [comment]
@Kenneth-Sills I started using the 1st-party JSON plugin (I believe the ESLint's creator copied this one after I opened an unrelated issue then he spied on my config) but thank you for fixing

**Comment by adamlui** [comment]
(normally I don't reward such behavior because i too experience a lot of leechery from copycats and understand the pain but 1st party means it will be more maintained/updated to me)
