### ISSUE TITLE
You should add "parserOptions.extraFileExtensions" to your config

### ISSUE THREAD

**Issue by Hussain-Ruhullah** [ota-meshi/eslint-plugin-json-schema-validator#59]
if I give the following command in terminal 
eslint ./test.json --fix

I get: 

  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: test.json.
The extension for the file (.json) is non-standard. You should add "parserOptions.extraFileExtensions" to your config

WHY?

thanks in advance

✖ 1 problem (1 error, 0 warnings)

**Comment by ota-meshi** [comment]
Would you please share a reproducible repository? Otherwise I will not be able to find out the cause of your problem.

**Comment by Hussain-Ruhullah** [comment]
Thanks you for fast reply,
you can find the package code [here](https://gitlab.com/Hussain-Ruhullah/linteverything)
use npm link command to link my project to any node project.
create a test.json file in your project and run eslint ./test.json 
please let me know if this text is not clear

**Comment by ota-meshi** [comment]
I'm not sure because building your repository seems to take complicated steps.
Could you make it reproducible just by doing `npm ci` and `npm run foo`?

**Comment by Hussain-Ruhullah** [comment]
the problem was the parser, let's close this issue
thanks

**Comment by alexnix** [comment]
Hi, what was the solution here? 
I am a bit confused because i have seen this plugin does override the parser configuration for .json files, so ` @typescript-eslint/parser` should not pick them ?
