### ISSUE TITLE
Including a custom schema

### ISSUE THREAD

**Issue by jnewc** [ota-meshi/eslint-plugin-json-schema-validator#73]
How would I go about validating a given JSON file against a custom schema? i.e. one provided in my own project and not in the schemastore.

**Comment by ota-meshi** [comment]
For example, you configure the rule as follows:

```json5
    "json-schema-validator/no-invalid": [
        "error",
        {
            "schemas": [
                {
                    "fileMatch": [".your-rc.json", ".your-rc.yaml"],
                    "schema": "path/to/custom-schema.json"
                }
            ]
        }
    ]
```

https://ota-meshi.github.io/eslint-plugin-json-schema-validator/rules/no-invalid.html#options

**Comment by jnewc** [comment]
Thank you, that appears to have worked, however:

`Draft 2019-09 schemas are not yet fully supported.`

Does this imply that no further validation will be run on matching files?

**Comment by jnewc** [comment]
Resolved by adding `json` to the vscode eslint validator config, per the readme.
