### ISSUE TITLE
[Bug] context.parserServices.defineTemplateBodyVisitor is not a function

### ISSUE THREAD

**Issue by jnewc** [ota-meshi/eslint-plugin-json-schema-validator#76]
I'm seeing the same issue for this plugin that is occurring here: https://github.com/ota-meshi/eslint-plugin-jsonc/issues/31

I've added `vue-eslint-parser` and `eslint-plugin-vue` as dev dependencies but the problem remains.

For now I've manually disabled the individual rules from the `vuejs-accessibility` but this is quite a brittle workaround.

I also have the following in my eslintrc:

```
"overrides": [
    {
      "files": ["*.json", "*.jsonc", "*.json5", "*.json6"],
      "parserOptions": {
        "parser":"jsonc-eslint-parser",
      }
    }
  ],
```

**Comment by ota-meshi** [comment]
Thank you for posting the issue.

Does the error message display the `vuejs-accessibility` rule?
If so, I think it's a bug in `vuejs-accessibility`. I think there is a problem if the `vuejs-accessibility` rule is enabled in a file other than the vue file. I had the same problem with `eslint-plugin-vue`, but it has been fixed.

As a workaround, I think you need to configure the offending rule to be enable only in .vue.

```json
"rules": {
  "vuejs-accessibility/rule-name": "off"
},
"overrides": [
  {
    "files": ["*.vue"],
    "rules": {
      "vuejs-accessibility/rule-name": "error"
    }
  }
]
```

**Comment by ota-meshi** [comment]
This is a bug in eslint-plugin-vuejs-accessibility. The value is `undefined`, so it will not enter the branch.

https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility/blob/1f658d50d0ebc5b2eb9990f0de57e395d8ad7075/src/utils/defineTemplateBodyVisitor.ts#L16

```diff
-  if (context.parserServices.defineTemplateBodyVisitor === null) {
+  if (context.parserServices.defineTemplateBodyVisitor == null) {
```

**Comment by ota-meshi** [comment]
I closed this issue because I opened the PR.
https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility/pull/190

**Comment by jnewc** [comment]
Hey, apologies, I'm a bit late coming back to this - but to answer your question:

> Does the error message display in vuejs-accessibility rule?

Yes it does, and omitting each vuejs-accessibility rule does prevent the issue, so your assumptions were correct. 

Thanks for the fix!
