### ISSUE TITLE
setting the plug in to match specific json files to a specific local schema

### ISSUE THREAD

**Issue by Talaween** [ota-meshi/eslint-plugin-json-schema-validator#80]
I would like to setup the plugin with ESLint so that eslint command report any error when matching specific json files in the project to a schema I have created,  however, I have a problem setting the plugin correctly, 
my schema is inside a folder called config and its called config.schema.json, while the files I would like to match are inside subfolders and all called  config.json.

I have the following in .eslintrc.js file:

```
 extends: [
         //
        'plugin:json-schema-validator/recommended',
    ],
  rules: {
       'json-schema-validator/no-invalid': [
            'error',
            {
                schemas: [
                    {
                        fileMatch: ['config/ing/config.json'],
                        schema: 'config/config.schema.json',
                    },
                ],
            },
        ],
}
```
I have enabled checking json file in .vscode/settings.js,

the problems I am facing are:
1- it doesn't match the specified json files to the schema and report errors.
2- there is a file called version.json in src folder the plugin keeps trying to match it to an online schema
p.s, if I put in the fileMatch field for schemas rule the .eslitrc.js it will work and tries to compare .eslintrc.js to my schema

**Comment by ota-meshi** [comment]
Due to a bug in this plugin, it may not work unless you specify:

```diff
                schemas: [
                    {
-                        fileMatch: ['config/ing/config.json'],
+                        fileMatch: ['/config/ing/config.json'],
                        schema: 'config/config.schema.json',
                    },
                ],
```

This is a bug and I would like to fix it to work with your configuration.

**Comment by ota-meshi** [comment]
I have released a fixed version, so please use the latest version.
If you don't want to check `version.json`, you should use `"useSchemastoreCatalog": false`.

**Comment by Talaween** [comment]
thank you for your help:

1- it works now after your fix and detects error in the specified file, however it only matches with file with .js files (module.exports or export default) with a valid js object, it ignores the .json files. even though I have this in .vscode/settings.js:

`    "eslint.validate": ["javascript", "javascriptreact", "typescript", "typescriptreact", "html", "json", "json5", "jsonc"],
`
and this is my eslint command:

`        "lint:js": "eslint --ext .ts,.tsx,.js,.json --quiet .",
`
2- setting schema store to false in the rule worked fine thank you.

```
'json-schema-validator/no-invalid': [
            'error',
            {
                schemas: [
                    {
                        fileMatch: ['config/ing/config.json'],
                        schema: 'config/config.schema.json',
                    },
                ],
                useSchemastoreCatalog: false,
            },
        ],
```

**Comment by ota-meshi** [comment]
> 1- it works now after your fix and detects error in the specified file, however it only matches with .js files (that exporting a js object via module.exports or export default), it ignores the .json files. even though I have this in .vscode/settings.js:

I don't know the cause of your problem. Can you share your repository that can reproduce the your problem?
